// DO NOT EDIT THIS FILE

#ifndef _G4D_PLANETERRAIN_H
#define _G4D_PLANETERRAIN_H

#define G4D_PLANETERRAIN_VERSION 0

#ifdef XENON_GAME // Only defined within the game's source code. Do NOT define XENON_GAME in your mod.
	#include "G4D_Planeterrain.hh"
#else
	#define G4D_PLANETERRAIN_DEFINE(...) 
	#ifdef __cplusplus
		extern "C" int _G4D_Planeterrain_VERSION() {return G4D_PLANETERRAIN_VERSION;}
		#define G4D_FUNCTION(F) extern "C" void F (struct F ## _PARAMS * Params_)
	#else
		int _G4D_Planeterrain_VERSION() {return G4D_PLANETERRAIN_VERSION;}
		#define G4D_FUNCTION(F) void F (struct F ## _PARAMS * Params_)
	#endif
	#define PARAM (*Params_)
#endif

///////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef XENON_GAME
	#define GLM_FORCE_INTRINSICS
	#define GLM_FORCE_SIMD_AVX2
	#define GLM_FORCE_CXX17
	#define GLM_FORCE_RADIANS
	#define GLM_FORCE_DEPTH_ZERO_TO_ONE
	#define GLM_ENABLE_EXPERIMENTAL
#endif
#include <glm/glm.hpp>

using namespace glm;

struct MakeTerrain_PARAMS {
	double in_baseRadius;
	double in_heightVariation;
	uint64_t out_index;
	double out_hydrosphereRadius;
	const char* out_computeShader;
	// const char* out_surfaceShader;
};

struct GetTerrainHeightMap_PARAMS {
	dvec3 in_normalizedPos;
	uint64_t in_index;
	double out_height;
};


G4D_PLANETERRAIN_DEFINE(
	MakeTerrain
	,GetTerrainHeightMap
)


#endif

/* 
	1. Get yourself an official VENDOR name on the official website
	
	2. Come up with a name for your mod that is all lowercase with a maximum of 12 alphanumeric characters, starting with a letter
	
	For the following, replace words in square brackets [] with your information without the brackets

	4. Create a directory [path_to_game]/modules/[MYVENDOR]_[mymod]/

	5. Create a file [mymod].c in that directory that will contain the source code for your mod
	
		Example source code in [mymod].c:
			
			#include "../G4D_Planeterrain.h" // add this exact line once at the very beginning of your source code
			
			G4D_FUNCTION( Load ) {
				// this code will be executed when your mod is loaded
			}
			
			G4D_FUNCTION( Unload ) {
				// this code will be executed when your mod is unloaded
			}
			
			//... more functions defined in documentation

	6. Compile your mod with the following command: gcc -shared -o [MYVENDOR]_[mymod].G4D_Planeterrain.[dll|so] [mymod].c
	
	7. Add [MYVENDOR]_[mymod] to the list of enabled mods in Galaxy4D-data/mods.txt
	
	8. Enjoy your mod!
*/

