[celestial]
base_radius =  6200000 ; meters
outer_radius = 6300000
gravity_acceleration = 9.8 ; m/s2

[terrain]
height_variation = 10000 ; meters

[atmosphere]
density_at_surface = 1.225 ; kg/m3
mie_scattering_coefficient = 0.000001
g = -0.7
temperature_at_surface = 290 ; kelvin

[atmosphere_composition]
; By mole fractions, given arbitrary number of molecules they will be automatically re-normalized to 100% by the engine
N = 78.08
O2 = 20.95
Ar = 0.93
CO2 = 0.03
H2O = 0.01
