[celestial]
base_radius =  6200000 ; meters
outer_radius = 6400000
gravity_acceleration = 9.8 ; m/s2
; orbit_distance_min = 99999km
; orbit_distance_max = 1942953km
; rotation_period = 4h

[atmosphere]
density_at_surface = 1.225 ; kg/m3
mie_scattering_coefficient = 0.000001
g = -0.5
temperature_at_surface = 290 ; kelvin

; [liquidsphere]
; sealevel = 6200km
; composition = H2O

[terrain]
height_variation = 10000 ; meters
